version: 2.1
commands:
  CloudformationDeploy:
    parameters:
      stackName:
        type: string
        default: myStack-${CIRCLE_WORKFLOW_ID:0:5}
      path:
        type: string
    steps:
      - run:
          name: deploy Stack
          command: |
            aws cloudformation deploy \
            --stack-name <<parameters.stackName>> \
            --template-body file://<<parameters.stackName>> \
            --region=us-east-1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print_workflowID:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo ${CIRCLE_WORKFLOW_ID:0:5}
      - run: echo ${CIRCLE_WORKFLOW_ID}

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print_workflowID
