version: 2.1
commands:
  cloudformation-deploy:
    parameters:
      stackName:
        type: string
        default: myStack-${CIRCLE_WORKFLOW_ID:0:5}
      path:
        type: string
    steps:
      - run:
          name: deploy Stack
          command: |
            aws cloudformation deploy \
              --stack-name <<parameters.stackName>> \
              --template-file file://<<parameters.stackName>> \
              --region=us-east-1

jobs:
  SayHello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  DeployInfrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - cloudformation-deploy:
          path: "serversConfigurations.yml"


workflows:
  say-hello-workflow:
    jobs:
      - SayHello
      - DeployInfrastructure
