---
- name: update dependencies cache
  become: yes
  apt:
    update_cache: yes

- name: upgrade dependencies
  become: yes
  apt:
    upgrade: yes

- name: remove useless dependencies
  become: yes
  apt:
    autoremove: yes

- name: install Nodejs & npm
  apt:
    name: [nodejs, npm]
    state: latest
    update_cache: yes

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create web directory
  file:
    path: ~/web
    state: directory

- name: set the app files to web directory
  copy:
    src: index.js
    dest: ~/web/index.js

- name: start web server
  shell: |
    pm2 start ~/web/index.js -f
